In [1]:
import numpy as np

In [2]:
vec = np.array([1, 2, 3, 4, 5])
print("Vector:", vec)
print("Shape of the vector:", vec.shape)

Vector: [1 2 3 4 5]
Shape of the vector: (5,)


In [7]:
class C:
    x = 5
    def f(self):
        return self.x 
o1 = C()

In [ ]:
mat2 = np.array([['1', 2, 3], 
                [4, 5, 6],
                [9, 8, 7]])
print(mat2.dtype)
mat2

<U21


array([['1', '2', '3'],
       ['4', '5', '6'],
       ['9', '8', '7']], dtype='<U21')

In [ ]:
fmat = mat2.astype(float)
fmat.dtype
fmat

array([[1., 2., 3.],
       [4., 5., 6.],
       [9., 8., 7.]])

In [16]:
mat2 = np.array([[1, 2, 3], 
                [4, 5, 6],
                [9, 8, 7]])
mat2[1,2]

np.int64(6)

In [17]:
m1 = np.zeros((3,4))
m2 = np.ones((2,3))
np.savez('my_arrays.npz', array1=m1, array2=m2)

In [18]:
with np.load('my_arrays.npz') as data:
    mat1 = data['array1']
    mat2 = data['array2']

print("Matrix 1:\n", mat1)
print("Matrix 2:\n", mat2)

Matrix 1:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Matrix 2:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [19]:
"""Reshape a numpy array to the specified number of rows and columns.
    
    Parameters:
        arr (np.ndarray): The input array to reshape.
        rows (int): The desired number of rows. Default is -1 (unspecified).
        cols (int): The desired number of columns. Default is -1 (unspecified).
        
    Returns:
        np.ndarray: The reshaped array."""
    
def array_reshape(arr, rows = -1, cols = -1):
    try:
        arr = np.array(arr)
        reshaped_arr = arr.reshape(rows, cols)
        return reshaped_arr
    except ValueError:
        print("Error: Invalid shape. The total number of elements in the array must remain the same.")
        return None

In [20]:
vec = np.array([1, 2, 3, 4, 5, 6])
print("Original Vector:", vec)
reshaped_matrix = array_reshape(vec, rows=2, cols=3)
print("Reshaped Matrix:")
print(reshaped_matrix)

Original Vector: [1 2 3 4 5 6]
Reshaped Matrix:
[[1 2 3]
 [4 5 6]]


In [24]:
v = np.array([1, 2, 3, 4, 5])
np.all(v > 0)

np.True_

In [26]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([1, 2, 0, 4, 5])

np.isclose(v1, v2,atol=1)

array([ True,  True, False,  True,  True])

In [27]:
v = np.array([10, 25, 37, 54, 65]) 
condition = v >= 40
print(condition)

[False False False  True  True]


In [ ]:
v = np.array([10, 25, 37, 54, 65]) 
condition = v >= 40
conditional_access = v[condition]
print(condition)
print("Values meeting the condition:", conditional_access)

[False False False  True  True]
Values meeting the condition (>= 40): [54 65]


In [29]:
v = np.array([10, 25, 37, 54, 65]) 
condition = v >= 40
new_array = np.where(condition, v, -1)
print("Original array:", v)
print("Condition array:", condition)
print("New array with -1 where condition is False:", new_array)

Original array: [10 25 37 54 65]
Condition array: [False False False  True  True]
New array with -1 where condition is False: [-1 -1 -1 54 65]
