In [6]:
print("Hello Pandas!")

Hello Pandas!


In [7]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import pandas as pd

In [10]:
data = [
    [1, 'Alice', 25],
    [2, 'Bob', 30],
    [3, 'Charlie', 35],
    [4, 'David', 40]
]
df = pd.DataFrame(data, columns=['ID', 'Name', 'Age'])
df

ID     Name  Age
0   1    Alice   25
1   2      Bob   30
2   3  Charlie   35
3   4    David   40

In [15]:
data_dict = {
    'ID': [1, 2, 3, 4],
    'Salary': [50000, 60000, 70000, 80000],
    'Department': ['HR', 'Finance', 'IT', 'Marketing']
    }

df2 = pd.DataFrame(data_dict)
display(df2)
df2.columns
df2.shape
df2.dtypes

ID  Salary Department
0   1   50000         HR
1   2   60000    Finance
2   3   70000         IT
3   4   80000  Marketing

ID            int64
Salary        int64
Department      str
dtype: object

In [16]:
df2['Salary']

0    50000
1    60000
2    70000
3    80000
Name: Salary, dtype: int64

In [18]:
def chk(df,type):
    return df[type].dtype

In [19]:
df2['Department'] = df2['Department'].astype('category')
chk(df2,'Department')

CategoricalDtype(categories=['Finance', 'HR', 'IT', 'Marketing'], ordered=False, categories_dtype=str)

In [20]:
df2.describe()

ID        Salary
count  4.000000      4.000000
mean   2.500000  65000.000000
std    1.290994  12909.944487
min    1.000000  50000.000000
25%    1.750000  57500.000000
50%    2.500000  65000.000000
75%    3.250000  72500.000000
max    4.000000  80000.000000

In [21]:
df.columns

Index(['ID', 'Name', 'Age'], dtype='str')

In [22]:
df['Age'].unique()

array([25, 30, 35, 40])

In [24]:
df2['Salary'].nunique()


4

In [25]:
df2['Salary'].max()

np.int64(80000)

In [26]:
df2['Salary'].min()

np.int64(50000)

In [27]:
df2['Salary'].idxmax()

3

In [28]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   ID          4 non-null      int64   
 1   Salary      4 non-null      int64   
 2   Department  4 non-null      category
dtypes: category(1), int64(2)
memory usage: 232.0 bytes


In [30]:
df2['Salary'].sum()

np.int64(260000)

In [31]:
df2['Salary'].values

array([50000, 60000, 70000, 80000])

In [32]:
df2.values

array([[1, 50000, 'HR'],
       [2, 60000, 'Finance'],
       [3, 70000, 'IT'],
       [4, 80000, 'Marketing']], dtype=object)

In [33]:
df2.replace(60000, 65000)

ID  Salary Department
0   1   50000         HR
1   2   65000    Finance
2   3   70000         IT
3   4   80000  Marketing

In [38]:
df.iloc[2,1]

'Charlie'

In [40]:
df['Age'].iloc[0:2]

0    25
1    30
Name: Age, dtype: int64

In [41]:
df.iloc[:, 0:2]

ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David

In [44]:
null = df.isnull()
null.sum()

ID      0
Name    0
Age     0
dtype: int64

In [52]:
import numpy as np
data = [
    [1, 'Alice', 25],
    [np.nan, 'Bob', 30],
    [3, 'Charlie', 35],
    [4, 'David', np.nan]
]
df = pd.DataFrame(data, columns=['ID', 'Name', 'Age'])
df

ID     Name   Age
0  1.0    Alice  25.0
1  NaN      Bob  30.0
2  3.0  Charlie  35.0
3  4.0    David   NaN

In [53]:
null = df.isnull().sum()
pd.DataFrame(null).T

ID  Name  Age
0   1     0    1

In [54]:
df.dropna()

ID     Name   Age
0  1.0    Alice  25.0
2  3.0  Charlie  35.0

In [56]:
df.dropna(subset=['ID'])

ID     Name   Age
0  1.0    Alice  25.0
2  3.0  Charlie  35.0
3  4.0    David   NaN

In [58]:
mean = df['Age'].mean()
df['Age'] = df['Age'].fillna(value=mean)
df

ID     Name   Age
0  1.0    Alice  25.0
1  NaN      Bob  30.0
2  3.0  Charlie  35.0
3  4.0    David  30.0

In [64]:
Header_col = ['index','age','gender','dept','postal code']
data=pd.read_table('http://bit.ly/movieusers',sep='|',header=None,names=Header_col)
data

index  age gender           dept postal code
0        1   24      M     technician       85711
1        2   53      F          other       94043
2        3   23      M         writer       32067
3        4   24      M     technician       43537
4        5   33      F          other       15213
..     ...  ...    ...            ...         ...
938    939   26      F        student       33319
939    940   32      M  administrator       02215
940    941   20      M        student       97229
941    942   48      F      librarian       78209
942    943   22      M        student       77841

[943 rows x 5 columns]

In [65]:
user_info=pd.read_csv('http://bit.ly/uforeports')
user_info.head()

City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [66]:
user_info.info()

<class 'pandas.DataFrame'>
RangeIndex: 18241 entries, 0 to 18240
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   City             18215 non-null  str  
 1   Colors Reported  2882 non-null   str  
 2   Shape Reported   15597 non-null  str  
 3   State            18241 non-null  str  
 4   Time             18241 non-null  str  
dtypes: str(5)
memory usage: 712.7 KB


In [68]:
user_info['Location'] = user_info.City + ', ' + user_info.State
user_info.head()

City Colors Reported Shape Reported State             Time  \
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00   
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00   
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00   
3               Abilene             NaN           DISK    KS   6/1/1931 13:00   
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00   

                   Location  
0                Ithaca, NY  
1           Willingboro, NJ  
2               Holyoke, CO  
3               Abilene, KS  
4  New York Worlds Fair, NY

In [70]:
user_info.rename(columns={'Colors Reported':'Colors_Reported'})

City Colors_Reported Shape Reported State  \
0                    Ithaca             NaN       TRIANGLE    NY   
1               Willingboro             NaN          OTHER    NJ   
2                   Holyoke             NaN           OVAL    CO   
3                   Abilene             NaN           DISK    KS   
4      New York Worlds Fair             NaN          LIGHT    NY   
...                     ...             ...            ...   ...   
18236            Grant Park             NaN       TRIANGLE    IL   
18237           Spirit Lake             NaN           DISK    IA   
18238           Eagle River             NaN            NaN    WI   
18239           Eagle River             RED          LIGHT    WI   
18240                  Ybor             NaN           OVAL    FL   

                   Time                  Location  
0        6/1/1930 22:00                Ithaca, NY  
1       6/30/1930 20:00           Willingboro, NJ  
2       2/15/1931 14:00               Holyoke, CO  
3        6/1/1931 13:00               Abilene, KS  
4       4/18/1933 19:00  New York Worlds Fair, NY  
...                 ...                       ...  
18236  12/31/2000 23:00            Grant Park, IL  
18237  12/31/2000 23:00           Spirit Lake, IA  
18238  12/31/2000 23:45           Eagle River, WI  
18239  12/31/2000 23:45           Eagle River, WI  
18240  12/31/2000 23:59                  Ybor, FL  

[18241 rows x 6 columns]

In [71]:
user_info.columns = user_info.columns.str.replace(' ', '_')
user_info.columns

Index(['City', 'Colors_Reported', 'Shape_Reported', 'State', 'Time',
       'Location'],
      dtype='str')

In [72]:
user_info.head()

City Colors_Reported Shape_Reported State             Time  \
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00   
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00   
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00   
3               Abilene             NaN           DISK    KS   6/1/1931 13:00   
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00   

                   Location  
0                Ithaca, NY  
1           Willingboro, NJ  
2               Holyoke, CO  
3               Abilene, KS  
4  New York Worlds Fair, NY

In [73]:
# drop a city column
user_info.drop(columns=['City'])

Colors_Reported Shape_Reported State              Time  \
0                 NaN       TRIANGLE    NY    6/1/1930 22:00   
1                 NaN          OTHER    NJ   6/30/1930 20:00   
2                 NaN           OVAL    CO   2/15/1931 14:00   
3                 NaN           DISK    KS    6/1/1931 13:00   
4                 NaN          LIGHT    NY   4/18/1933 19:00   
...               ...            ...   ...               ...   
18236             NaN       TRIANGLE    IL  12/31/2000 23:00   
18237             NaN           DISK    IA  12/31/2000 23:00   
18238             NaN            NaN    WI  12/31/2000 23:45   
18239             RED          LIGHT    WI  12/31/2000 23:45   
18240             NaN           OVAL    FL  12/31/2000 23:59   

                       Location  
0                    Ithaca, NY  
1               Willingboro, NJ  
2                   Holyoke, CO  
3                   Abilene, KS  
4      New York Worlds Fair, NY  
...                         ...  
18236            Grant Park, IL  
18237           Spirit Lake, IA  
18238           Eagle River, WI  
18239           Eagle River, WI  
18240                  Ybor, FL  

[18241 rows x 5 columns]

In [ ]:
user_info.to_csv('test.csv')