In [3]:
import numpy as np

In [9]:
v1 = np.array([1, 2, 3])
v2 = np.array([1, 2, 3])  
result = v1 + v2
print(result) 

[2 4 6]


In [12]:
m1 = np.array([[1, 2, 3], 
               [4, 5, 6], 
               [7, 8, 9]])

m2 = np.array([[9, 8, 7], 
               [6, 5, 4], 
               [3, 2, 1]])

result_matrix = m1 + m2
print(result_matrix)
print(m1.shape)
print(m2.ndim)
print(result_matrix.shape)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
(3, 3)
2
(3, 3)


In [14]:
mat = np.array([[1.6, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

mat.dtype

dtype('float64')

In [15]:
x = 3.6
type(x)

float

In [ ]:
class c:
    x = 5

obj = c()


int

In [17]:
mat3 = np.array([[obj, 2, 3],
                 [4, 5, 6],    
                 [7, 8, 9]])

mat3.dtype

dtype('O')

In [ ]:
# Object ---> String ---> Float ---> Int ---> Bool

In [19]:
mat4 = np.array([[1, 2, 3],
                 [4, 5, 6],   
                 [7, 8, 9]])

float_mat4 = mat4.astype(float)
print(float_mat4)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [20]:
v = np.array([1, 0, 3, 0, 5])
v[2:5] 

array([3, 0, 5])